version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "rffontenelle"
    commit-message:
      prefix: "gha"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "rffontenelle"
    commit-message:
      prefix: "pip"
